### ISSUE TITLE
Modify Certificate Stylesheet to work with more themes and installations

### ISSUE THREAD

**Issue by actual-saurabh** [gocodebox/lifterlms#497]
With the current CSS, there are frequent instances and support requests for Certificates not displaying properly in print.

For example, this is how things are on the [Beans Framework](https://github.com/Getbeans/Beans) (I chose it because it's markup has a lot of divitis and is nothing like standard expected markup).

![Certificate Page](https://user-images.githubusercontent.com/1739834/39092600-3345934e-462f-11e8-842a-271f4d15a4c8.png)

This is how it looks on print command:

![Certificate Print in Chrome](https://user-images.githubusercontent.com/1739834/39092602-4a0308dc-462f-11e8-9fd9-473f7c9a22ed.png)

This is very common and reported at least in one ticket each day.

Instead, if I modify the print styles in certificate.css to do a couple of things, as follows:

```css
@media print { 

    @page{
        size: landscape;
    }

    /* Make everything on the page invisible */
    body *{
        visibility: hidden;
    }

   /* remove all headers, menus and footers */
    header, nav, footer{
        display:none;
    }
	
   /* make only the certificate container and its children visible
    .llms-certificate-container, .llms-certificate-container *{
        visibility: visible;
    }

    /* position certificate absolutely and center horizontally
    .llms-certificate-container{
            position: absolute;
            top: 0;
            left: 0;
            right: 0;
            margin: 0 auto;	
	}
}
```
This is what I get:

![After new CSS](https://user-images.githubusercontent.com/1739834/39092701-6a988912-4631-11e8-88fc-6a18fa19d7b4.png)

This works with Launchpad, Twenty Seventeen and a couple other standard and non-standard themes.

If this makes sense, I can send in a PR
