### ISSUE TITLE
Gap above lesson's video with the LaunchPad theme (or any other theme/plugin using fitvids.js)

### ISSUE THREAD

**Issue by eri-trabiccolo** [gocodebox/lifterlms#944]
### Reproduction Steps
With the latest LifterLMS version, latest LaunchPad theme version, and *no other* plugin installed:
- add a video to a whatever lesson using the Lesson Settings, Video Embed Url field:
![Schermata 2019-09-24 alle 14 22 22](https://user-images.githubusercontent.com/7689242/65511156-d89c4b80-ded6-11e9-9742-7cb0d4ef5cca.png)

- Update and view the lesson in front.

### Expected Behavior

No gap should appear above the video.

### Actual Behavior

Gap above the video.

![Schermata 2019-09-24 alle 14 25 17](https://user-images.githubusercontent.com/7689242/65511295-2913a900-ded7-11e9-8b2f-62b6fb7c2178.png)

This is due to the fact that the LaunchPad theme uses fitvids.js which wraps iframes into a div wrapper (`.fluid-width-video-wrapper`) with `position:relative` and `padding-top` dynamically calculated based on the video aspect ratio.
The above wrapper conflicts with the `.center-video` wrapper introduced recently in the llms code (https://github.com/gocodebox/lifterlms/commit/2432ea7efdbd4b0b6e9b1963cc0d22425f4b148b#diff-2318ead75e1f0479fced42ebde3cee10R28) which aims to the same goal, however assuming a fixed (16:9) aspect ratio: the gap is then the `.center-video` `padding-top`.

You should be able to reproduce with any other theme or plugin that uses fitvids.js (e.g. Divi) or that anyways wraps the iframe in a div for the same purpose.

We know the Astra theme does that too (https://github.com/gocodebox/lifterlms/issues/833) although **it's not impacted by this issue** because it does it using the filter hook `embed_oembed_html` which is not fired when generating the lesson's video iframe.
I'm taking this as an example to say that we cannot know for sure if and how 3rd parties will wrap iframes creating this kind of issue.

I think a possible solution would be adding the following style:
```css
.center-video > div:not([class*=llms-av-]) {
    height: 100%;
    left: 0;
    position: absolute;
    top: 0;
    width: 100%;
    padding-top: 0 !important;
}
```
I think this should cover most of the cases (excluding the llms advanced video stuff) and should not cause particular issues, which anyway, we can treat case by case.

The alternative, more prudent approach, would be treating only the cases we know for sure (fitvids.js conflict), so:

```css
.center-video .fluid-width-video-wrapper {
    height: 100%;
    left: 0;
    position: absolute;
    top: 0;
    width: 100%;
    padding-top: 0 !important;
}
```

Also note that this issue has been reported several times lately on helpscout.
I've talked with @nrherron92 after we saw a ticket reporting this was happening on a site running the LaunchPad theme, but maybe she knows about other cases where fitvids.js was not involved.

Since we're brave I think we can safely go with the... prudent approach :) 
what do you think?

### Error Messages / Logs

n/a

### System Information

n/a

### Browser, Device, and Operating System Information

n/a
