### ISSUE TITLE
Gap above lesson's video with self hosted videos

### ISSUE THREAD

**Issue by eri-trabiccolo** [gocodebox/lifterlms#964]
### Reproduction Steps

With the latest LifterLMS version, latest LaunchPad theme version, and no other plugin installed:

- add a self-hosted video to a whatever lesson using the Lesson Settings, Video Embed Url field.
- Update and view the lesson in front.

### Expected Behavior

No gap should appear above the video.

### Actual Behavior

Gap above the video.
![Schermata 2019-10-18 alle 10 42 13](https://user-images.githubusercontent.com/7689242/67079716-fab28200-f193-11e9-9955-94ff423d24f5.png)

See also https://github.com/gocodebox/lifterlms/issues/944

Once again the solution can be generic:

```css
.center-video > div:not([class*=llms-av-]) {
    height: 100%;
    left: 0;
    position: absolute;
    top: 0;
    width: 100% !important; /*overrides the inline .wp-video style*/
}
```
or more specific/prudent

```css
.center-video > .wp-video {
    height: 100%;
    left: 0;
    position: absolute;
    top: 0;
    width: 100% !important; /*overrides the inline .wp-video style*/
}
```

I'm going to propose the specific/prudent solution once again, and we'll see in the future if more cases come so to make us consider to switch to the generic one.

**Comment by eri-trabiccolo** [comment]
@thomasplevy 
the PR #965 won't solve the issue of the user here:
https://wordpress.org/support/topic/latest-version-whitespace-between-video-and-header/
as it addresses only the `.wp-video` wrappers, while the user video has this kind of structure:
![Schermata 2019-10-21 alle 12 40 36](https://user-images.githubusercontent.com/7689242/67198980-6f89f400-f400-11e9-8604-418a2a52f6b3.png)

I'm not sure how to reproduce it but I guess that #944 applied on `.wistia_responsive_padding` would fix it. Otherwise we have to replace #944 and #965 with the generic compatibility code:

```css
.center-video > div:not([class*=llms-av-]) {
    height: 100%;
    left: 0;
    position: absolute;
    top: 0;
    width: 100% !important; /*overrides the inline .wp-video style*/
    padding-top: 0 !important; /*overrides any inner repsonsive wrappers inline style*/
}

```

p.s. #965 solves the issue reported by another user using self-hosted videos.
